routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return view('welcome');
});

Route::delete('/bags/empty','BagController@empty')->name('bags.empty');

Route::resource('categories', 'CategoryController');
Route::resource('titles', 'TitleController');
Route::resource('assets', 'AssetController');
Route::resource('bags','BagController');
Route::resource('tickets','TicketController');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/BagController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Session;
use App\Title;
use App\Asset;

class BagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(Session::has('bag')){
        // get all ids of bag session
            $title_ids = array_keys(Session::get('bag'));
        // query on database
            $titles = Title::find($title_ids);
            // dd($titles);
            // $total = 0;

            // foreach ($titles as $title) {
            //     // $title->needed = date('Y-m-d',strtotime(Session::get("bag.n$title->id")));
            //     $title->needed = Session::get("bag.$title->id.0");
            //     $title->returned = Session::get("bag.$title->id.1");
            //     // $title->returned = date('Y-m-d',strtotime(Session::get("bag.r$title->id")));
            // }
            
            // dd(Session::get("bag.r2"));
            return view('bags.index')->with('titles',$titles);
        } else {
            return view('bags.index');
        }


    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $bag)
    {
        // $request->validate([
        //     'needed' => 'required|date|after:yesterday',
        //     'returned' => 'required|date|after:yesterday'

        // ]);
        // $needed = $request->input('needed');
        // dd($needed);
        // $returned = $request->input('returned');
        // store to session_abort()
        
        $request->session()->put("bag.$bag");
        // $request->session()->put("bag.$bag", $returned);

        // dd(Session::get('bag'));
        return redirect(route('bags.index'));

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $bag)
    {
        // Session::forget("bag.$bag");

        $request->session()->forget("bag.$bag");
        if(count($request->session()->get('bag')) == 0) {
            $request->session()->forget('bag');
        }

        return redirect(route('bags.index'))->with('status','Product removed from bag');
    }

    public function empty()
    {
        Session::forget('bag');
        return redirect(route('bags.index'))->with('status','bag has been cleared');

    }
}

resources/views/bags/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
	<h3>My Bag</h3>
	@if(Session::has('status'))
	<div class="alert alert-success text-center w-100">{{Session::get('status')}}</div>
	@endif
	{{-- @include('titles.includes.error-status') --}}
	<div class="row">
		<div class="col-12">
		</div>
		@if(Session::has('bag'))
		<div class="col-12 col-md-8">
			{{-- table --}}
			<div class="table-responsive">
				<table class="table table-striped table-hover text-center">
					<thead>
						<th scope="col" colspan="3">Book</th>
						<th scope="col">Actions</th>
					</thead>
					<tbody>
						{{-- start of row --}}
						@foreach($titles as $title)
						<tr>
							<th scope="row" colspan="3">{{$title->name}}</th>
							<td>
								<form action="{{route('bags.destroy', ['bag'=>$title->id])}}" method="POST">
									@csrf
									@method('DELETE')
									<button class="btn-sm btn-danger">Remove from bag</button>
								</form>
							</td>

							
						</tr>
						@endforeach
						{{-- end of row --}}
					</tbody>
					<tfoot>
						<tr>
							<td>
								<form action="{{route('bags.empty')}}" method="POST">
									@csrf
									@method('DELETE')
									<button class="btn-sm btn-danger">Clear bag</button>
								</form>
							</td>
							<td></td>
							<td></td>
							<td></td>
								
							<div id="paypal-btn"></div>
							{{-- @endcan --}}
							{{-- @cannot('isLogged') --}}
							{{-- 				<a href="{{route('login')}}"><button class="btn-sm btn-primary w-100">Send request</button></a> --}}

							{{-- @endcannot	 --}}
						</td>
					</tr>
				</tfoot>
			</table>
		</div>
	</div>
	<div class="col-12 col-md-4 border-left">
		@if($errors->has('date'))
		
		<p class="text-danger"><span class="small" >{{ $errors->first('date')}}</span></p>
		
		@endif
		{{-- <h5>Request Form</h5> --}}
		{{-- <hr> --}}
		<form action="{{route('tickets.store')}}" method="post" >
			@csrf
			<div class="form-group">
				<label for="needed" class="my-2">Date needed:</label>
				<input type="date" name="needed" id="needed" class="form-control-sm my-2" min="{{date('Y-m-d')}}" value="{{old('needed')}}">
				@if($errors->has('needed'))
				
				<p class="text-danger"><span class="small" >{{ $errors->first('needed')}}</span></p>
				
				@endif
			</div>

			<div class="form-group">
				<label for="returned" class="my-2">Date returned:</label>
				<input type="date" name="returned" id="returned" class="form-control-sm my-2" min="{{date('Y-m-d')}}" value="{{old('returned')}}">
				@if($errors->has('returned'))
				
				<p class="text-danger"><span class="small" >{{ $errors->first('returned')}}</span></p>
				
				@endif
			</div>
			<button class="btn-sm btn-primary">Submit request</button>
		</form>
	</form>
</div>
{{-- end of table --}}
@else
<div class="alert alert-info text-center mx-auto w-100">BookBag is empty</div>
@endif
</div>
</div>



@endsection