routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return view('welcome');
});

Route::delete('/bags/empty','BagController@empty')->name('bags.empty');

Route::resource('categories', 'CategoryController');
Route::resource('titles', 'TitleController');
Route::resource('assets', 'AssetController');
Route::resource('bags','BagController');
Route::resource('tickets','TicketController');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Asset.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Asset extends Model
{
    public function title()
    {
        return $this->belongsTo('App\Title');
    }
    public function asset_status()
    {
        return $this->belongsTo('App\AssetStatus');
    }
    
    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function tickets()
    {
    	return $this->belongsToMany('App\Ticket','asset_ticket')
    		->withPivot('asset_code');
    }
}

app/Http/Controllers/AssetController.php
<?php

namespace App\Http\Controllers;

use App\Asset;
use App\Title;
use App\User;
use App\AssetStatus;
use Str;
use Illuminate\Http\Request;

class AssetController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Asset $asset)
    {
        $this->authorize('viewAny',$asset);

        $assets = Asset::orderBy('title_id','asc')->orderBy('asset_code','asc')->get();
       return view('assets.index')->with('assets',$assets);
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Asset $asset)
    {
        $this->authorize('create',$asset);
        
        return view('assets.create')->with('titles',Title::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Asset $asset)
    {
        $this->authorize('create',$asset);

        $request->validate([
            'name' => 'required',
            'quantity' => 'required|min:1'
        ]);

        for($i = 0; $i < $request->input('quantity'); $i++) {
           $asset = new asset;
           $asset->title_id = $request->input('name');
           $asset->asset_status_id = 1;
           $asset->save();

           $title = Title::find($request->input('name'));
           $asset->asset_code = sprintf("%03s",strval($asset->title_id)).sprintf("%04s", strval($asset->id));

           $asset->save();
       }
       
       $stocks = Asset::all()->whereIn('title_id',$request->input('name'))->whereIn('asset_status_id',1);
       $title = Title::find($request->input('name'));
       $title->stock = count($stocks);

       if (count($stocks)) {
            $title->title_status_id = 1;
       }



        // return redirect(route('assets.index'));
       return redirect(route('assets.index'));
   }

    /**
     * Display the specified resource.
     *
     * @param  \App\Asset  $asset
     * @return \Illuminate\Http\Response
     */
    public function show(Asset $asset)
    {
        $this->authorize('view',$asset);

        return view('assets.show')->with('asset',$asset);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Asset  $asset
     * @return \Illuminate\Http\Response
     */
    public function edit(Asset $asset)
    {
        // return "Edit";
        $this->authorize('update',$asset);

        return view('assets.edit')->with('asset',$asset)->with('statuses',AssetStatus::all())->with('users',User::all()->whereIn('role_id',[2]));
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Asset  $asset
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Asset $asset)
    {
        $this->authorize('update',$asset);

         if ($request) {
            $request->validate([
                'status' => 'required',
                'user' => 'required'
            ]);
        }

        $asset->asset_status_id = $request->input('status');
        if($request->input('user') === 'NULL') {
            $asset->user_id = null;
        } else {
            $asset->user_id = $request->input('user');
        }
        $asset->save();
        return view('assets.show')->with('asset',$asset);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Asset  $asset
     * @return \Illuminate\Http\Response
     */
    public function destroy(Asset $asset)
    {
        $this->authorize('delete',$asset);

        $asset->delete();
        return redirect(route('assets.index'));
    }
}

resources/views/assets/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
	<div class="row">
		<div class="col-12 col-md-8 mx-auto">
			<h3>Add Assets</h3>
			<hr>
			<form action="{{route('assets.store')}}" method="post">
				@csrf
				<div class="form-group">
					<label for="name">Title</label>
					<select name="name" id="name" class="form-control-sm bg-white">
						@foreach($titles as $title)
						<option value="{{$title->id}}">{{$title->name}}</option>
						@endforeach
					</select>
				</div>
				<div class="form-group">
					<label for="qty">Quantity</label>
					<input type="number" name="quantity" id="quantity" min="1" class="form-control-sm">
					@if($errors->has('quantity'))
                    
                    
                    <p class="text-danger"><span class="small" >{{ $errors->first('quantity')}}</span></p>
                    
                @endif   
				</div>
				<button class="btn-sm btn-info p-2">Add assets</button>
			</form>
		</div>
	</div>
</div>

@endsection

resources/views/assets/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-12 col-md-8 mx-auto">
           <h3>{{$asset->title->name}}</h3>
           <small>Asset Code: {{$asset->asset_code}}</small>
           <hr>

           <form action="{{route('assets.update',['asset' => $asset->id])}}" method="post">
            @csrf
            @method('put')
            <div class="form-group my-0 py-0">
                <label for="status" class="">Asset Status</label>
                <select name="status" id="status" class="form-control-sm my-3 d-inline bg-white">
                    @foreach($statuses as $status)
                    <option value="{{$status->id}}" {{ $asset->asset_status_id == $status->id ? "selected": ""}}>{{$status->name}}</option>
                    @endforeach
                    
                </select>
                
            </div>
            <div class="form-group">
              <label for="user">User</label>
              <select name="user" id="user" class="form-control-sm my-3 d-inline bg-white">
                <option value="NULL">None</option>
                @foreach($users as $user)
                <option value="{{$user->id}}" {{ $asset->user_id == $user->id ? "selected": ""}}>{{$user->name}}</option>
                @endforeach
            </select>
            </div>
            <button class="btn-sm btn-primary">Update asset</button>                
        </form>
    </div>
</div>
</div>
@endsection

resources/views/assets/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
	<div class="row">
		<div class="col-12 mx-auto">
			<h3>Assets</h3>
			@include('assets.includes.asset-table')
		</div>
	</div>
</div>

@endsection

resources/views/assets/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-12 col-md-8 mx-auto">
			<h3>{{$asset->title->name}}</h3>
			<small>Asset Code: {{$asset->asset_code}}</small>
			<hr>
			<p>Status: {{$asset->asset_status->name}}</p>
			@if($asset->asset_status_id == 2 && $asset->user_id)
			<p>Currently used by: {{$asset->user->name}}</p>
			@endif
			<p>Created on @if($asset->created_at){{$asset->created_at->format('F d, Y')}}@else January 12, 2020 @endif</p>
			<p>Last updated on @if($asset->updated_at){{$asset->updated_at->format('F d, Y')}}@else January 12, 2020 @endif</p>
			<a href="{{route('assets.edit',['asset' => $asset->id])}}"><button class="btn-sm btn-warning">Edit</button></a>
			<form action="{{route('assets.destroy',['asset' => $asset->id])}}" method="POST" class="d-inline">
				@csrf
				@method('DELETE')
				<button class="btn-sm {{$asset->asset_status_id == 4 ? "btn-danger" : ""}}" {{$asset->asset_status_id == 4 ? "" : "disabled"}}
				>Remove</button>
			</form>
		</div>
	</div>
</div>
@endsection